# -*- coding: utf-8 -*-
"""Cal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e123753SuKqvThHAj_PnyA4ReYUFwdWC
"""

#*** mean
list = [12, 16, 20, 20, 12, 30, 25, 23, 24, 20]
#print(list)
mean = sum(list) / len(list)
print(mean)

#*** Median 
#list = [12,16,20,20,12,30,25,23,24,20]
list.sort()
if len(list) % 2 == 0:
    m1 = list[len(list)//2]
    m2 = list[len(list)//2 - 1]
    median = (m1 + m2)/2
else:
    median = list[len(list)//2]
print(median)

##Mode
frequency = {}
for i in list:
    frequency.setdefault(i, 0)
    frequency[i]+=1
frequent = max(frequency.values())
for i, j in frequency.items():
    if j == frequent:
        mode = i
print(mode)