# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yfDsCeQnOH-gf1E5Z_BMOtQe8mN-G4Pn
"""

import random
n = random.randrange(1,10)
guess = int(input("Enter any number:")) 
while n!= guess:
    if guess < n:
       print("Too Low")
       guess = int(input("Enter number again:"))
    elif guess > n:
        print("Too high")
        guess = int(input("Enter number again:"))
    else : 
       break

print("You guessed it right!!")